import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Navbar from "../components/Navbar"
import Post from "../components/Post"
import Newsletter from "../components/Newsletter"

const Home: NextPage = () => {
  return (
    <div className="max-w-6xl m-auto font-Inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <h1 className="text-center py-20 text-3xl">Latest Blog Posts</h1>
      <div className="grid grid-cols-3 justify-items-center">
        <Post />
        <Post />
        <Post />
        <Post />
        <Post />
        <Post />
      </div>
      <div className="flex justify-center py-10">
      <button className="flex items-center text-[#1C6758] text-lg p-2">
        View More
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-6 h-6 ml-2"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3"
          />
        </svg>
      </button>

      </div>
      <Newsletter />
    </div>
  )
}

export default Home
